name: CI/CD - Build, Test, Docker push, Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm test

      # Preparar buildx (opcional para multi-arch)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: $!{{ secrets.DOCKERHUB_USERNAME }}
          password: $!{{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            $!{{ secrets.DOCKERHUB_USERNAME }}/mi-app-hola-mundo:${{ github.sha }}
            $!{{ secrets.DOCKERHUB_USERNAME }}/mi-app-hola-mundo:latest

      - name: Trigger Render deploy (image-backed service)
        env:
          RENDER_API_KEY: $!{{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: $!{{ secrets.RENDER_SERVICE_ID }}
          IMAGE: $!{{ secrets.DOCKERHUB_USERNAME }}/mi-app-hola-mundo:latest
        run: |
          echo "Triggering Render deploy for image $IMAGE"
          curl -X POST "https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys" \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Content-Type: application/json" \
            -d "{\"image\":\"docker.io/$IMAGE\"}"
